### PR TITLE
merges 3 open PR's

### PR DESCRIPTION
**Pull request by cristinamullin**
Merges 3 open PR's & includes updates related to #434:
https://github.com/USEPA/TADA/pull/434
https://github.com/USEPA/TADA/pull/436
https://github.com/USEPA/TADA/pull/435

@kathryn-willi I was not able to add any commits to your open PR, so I created a new branch from it and made some edits here. It may be because I do not have access to commit changes to your forked version of the repo which your original PR was created from. Can you double check that your new mapping function (TADA_ViewATTAINS) is still working correctly on this branch ("updates") with my edits? The others seem great, and everything is passing the tests (with one exception unrelated to your work that @hillarymarler is planning to dig into Friday). But when I run TADA_ViewATTAINS nothing draws on the map - I fear I may have broken something with my edits but haven't found the issue yet (you'll probably see the issue right away!). Any other feedback is welcome. Also, I just added you to our repo with "triage" privileges. I think this will allow me to select you as a reviewing on PR's like this in the future & for you to select me on yours. 

Overall, we think these functions are awesome & are excited to share them with the TADA user community! Thank you and your team for this incredibly valuable contribution!

Aiming to merge this in after you and @hillarymarler have time to review once more.

### CODE REVIEW

**Comment by cristinamullin** [comment]
@kathryn-willi 

Here are a few other thoughts/questions I had during my review... regarding potential future improvements/considerations (none needs to be addressed before merging in this PR):
- Include code at the top of test-GeospatialFunctions.R to easily update/replace the new associated test files in the testdata folder as part of routine maintenance if needed (for example, if changes are made to TADA_DataRetrieval)?
- I noticed the new functions use the WQP lat/lon columns instead of the TADA versions of those lat/lon columns which are the numeric versions. TADA creates these numeric versions of the lat/lon columns for use in TADA_FlagCoordinates() which looks as the how many numbers are to the right of the decimal and flags lat/lon as imprecise if there are less than 3. That function also flags results outside of the U.S. Let's discuss when to use the original vs TADA lat/lon columns - are both necessary? Keep in mind that the duplicates (originals) may be removed if there is a TADA equivalent and the user wants to reduce number of cols at the end of module 1. 
- All columns added typically have the TADA. prefix. TADA For the new ATTAINS columns, the ATTAINS. prefix makes sense. There is one additional column, "geometry" added by these functions. All columns created/referenced in TADA are also all included in the TADA_OrderCols() function in RequiredCols.R. All columns are placed in a specific order and this function is typically run within most TADA functions to keep the order.  Thoughts about changing this to "TADA.Geometry" and placing it near the lat/lon fields in the df column ordering? Is "geometry" better in this case because of how spatial data is referenced in R/sf?
- Is this message something that we can address or silence? "although coordinates are longitude/latitude, st_intersects assumes that they are planar". 
 ```r
> # TADA_GetATTAINS ----
> testthat::test_that(desc = "TADA_GetATTAINS can take in the TADA_dataframe and the sf object as inputs",
+                     code = {
+                       expect_no_error(TADA_GetATTAINS(.data = TADA_dataframe))
+                       expect_no_error(TADA_GetATTAINS(.data = TADA_spatial))
+                       
+                       expect_no_warning(TADA_GetATTAINS(.data = TADA_dataframe))
+                       expect_no_warning(TADA_GetATTAINS(.data = TADA_spatial))
+                     })
[1] "Your TADA data covers a large spatial range. The ATTAINS pull may take a while."
although coordinates are longitude/latitude, st_intersects assumes that they
are planar
[1] "Your TADA data covers a large spatial range. The ATTAINS pull may take a while."
although coordinates are longitude/latitude, st_intersects assumes that they
are planar
[1] "Your TADA data covers a large spatial range. The ATTAINS pull may take a while."
although coordinates are longitude/latitude, st_intersects assumes that they
are planar
[1] "Your TADA data covers a large spatial range. The ATTAINS pull may take a while."
although coordinates are longitude/latitude, st_intersects assumes that they
are planar
Test passed 

```

```r
[1] "Your TADA data covers a large spatial range. The ATTAINS pull may take a while."
although coordinates are longitude/latitude, st_intersects assumes that they are planar
> 
> TADA_with_ATTAINS <- TADA_GetATTAINS(.data = TADA_spatial, return_sf = FALSE)
[1] "Your TADA data covers a large spatial range. The ATTAINS pull may take a while."
although coordinates are longitude/latitude, st_intersects assumes that they are planar
```

**Comment by kathryn-willi** [comment]
> Merges 3 open PR's & includes updates related to #434: #434 #436 #435
> 
> @kathryn-willi I was not able to add any commits to your open PR, so I created a new branch from it and made some edits here. It may be because I do not have access to commit changes to your forked version of the repo which your original PR was created from. Can you double check that your new mapping function (TADA_ViewATTAINS) is still working correctly on this branch ("updates") with my edits? The others seem great, and everything is passing the tests (with one exception unrelated to your work that @hillarymarler is planning to dig into Friday). But when I run TADA_ViewATTAINS nothing draws on the map - I fear I may have broken something with my edits but haven't found the issue yet (you'll probably see the issue right away!). Any other feedback is welcome. Also, I just added you to our repo with "triage" privileges. I think this will allow me to select you as a reviewing on PR's like this in the future & for you to select me on yours.
> 
> Overall, we think these functions are awesome & are excited to share them with the TADA user community! Thank you and your team for this incredibly valuable contribution!
> 
> Aiming to merge this in after you and @hillarymarler have time to review once more.

@cristinamullin I think I was able to find the source of the empty map in TADA_ViewATTAINS...  looks like some `data =` arguments in the leaflet maps got swapped to .data, and a `data` object got overwritten. With those swaps (I've added them as suggestions that you should be able to commit easily) it should run now. 😄

**Comment by kathryn-willi** [comment]
* Include code at the top of test-GeospatialFunctions.R to easily update/replace the new associated test files in the testdata folder as part of routine maintenance if needed (for example, if changes are made to TADA_DataRetrieval)?

_Great idea, we can change this._

* I noticed the new functions use the WQP lat/lon columns instead of the TADA versions of those lat/lon columns which are the numeric versions. TADA creates these numeric versions of the lat/lon columns for use in TADA_FlagCoordinates() which looks as the how many numbers are to the right of the decimal and flags lat/lon as imprecise if there are less than 3. That function also flags results outside of the U.S. Let's discuss when to use the original vs TADA lat/lon columns - are both necessary? Keep in mind that the duplicates (originals) may be removed if there is a TADA equivalent and the user wants to reduce number of cols at the end of module 1.

_Yes, this is something we discussed in the ROSS team, as well! My old justification for using lat/lon (instead of TADA-ified lat/lon) was so that users could run the functions on datasets that weren't created using `autoclean = TRUE`. But, I am inclined to change this now that I see the value of always having TADA.Longitude/TADA.Latitude. For example, I can immediately use those flagging functions you've developed to ensure the geospatial computations are occurring across valid coordinates. (SIDE NOTE: I think this may actually be at least part of the issue that @hillarymarler encountered when running fetchATTAINS across Indiana... there's a wonky observation off the coast of Africa, so the function is trying to pull ATTAINS data across the whole eastern US.)

* All columns added typically have the TADA. prefix. TADA For the new ATTAINS columns, the ATTAINS. prefix makes sense. There is one additional column, "geometry" added by these functions. All columns created/referenced in TADA are also all included in the TADA_OrderCols() function in RequiredCols.R. All columns are placed in a specific order and this function is typically run within most TADA functions to keep the order.  Thoughts about changing this to "TADA.Geometry" and placing it near the lat/lon fields in the df column ordering? Is "geometry" better in this case because of how spatial data is referenced in R/sf?

_Spatial functions automatically store and look for geospatial information in a `geometry` column, so when this gets renamed, it does lead to issues downstream. Though we can rename this column and add code to handle geospatial functions within TADA, it will render the sf object unusable outside of any of the functions we write within this package._

* Is this message something that we can address or silence? "although coordinates are longitude/latitude, st_intersects assumes that they are planar".

_I added some messaging suppression as suggested edits!_

**Comment by cristinamullin** [comment]
> > Merges 3 open PR's & includes updates related to #434: #434 #436 #435
> > @kathryn-willi I was not able to add any commits to your open PR, so I created a new branch from it and made some edits here. It may be because I do not have access to commit changes to your forked version of the repo which your original PR was created from. Can you double check that your new mapping function (TADA_ViewATTAINS) is still working correctly on this branch ("updates") with my edits? The others seem great, and everything is passing the tests (with one exception unrelated to your work that @hillarymarler is planning to dig into Friday). But when I run TADA_ViewATTAINS nothing draws on the map - I fear I may have broken something with my edits but haven't found the issue yet (you'll probably see the issue right away!). Any other feedback is welcome. Also, I just added you to our repo with "triage" privileges. I think this will allow me to select you as a reviewing on PR's like this in the future & for you to select me on yours.
> > Overall, we think these functions are awesome & are excited to share them with the TADA user community! Thank you and your team for this incredibly valuable contribution!
> > Aiming to merge this in after you and @hillarymarler have time to review once more.
> 
> @cristinamullin I think I was able to find the source of the empty map in TADA_ViewATTAINS... looks like some `data =` arguments in the leaflet maps got swapped to .data, and a `data` object got overwritten. With those swaps (I've added them as suggestions that you should be able to commit easily) it should run now. 😄

@kathryn-willi Oops - thanks for catching these! I don't see any of your code edits/suggestions. Are you able to add comments or code suggestions to this open PR (files changed tab)? Or commit directly to this PR? I wonder if the permissions are still not working as we'd like.

**Review by kathryn-willi — CHANGES_REQUESTED** [review]
Please see my suggested edits for fixing `TADA_ViewATTAINS()`. Hopefully you can see these now!

**Comment by cristinamullin** [comment]
> * Include code at the top of test-GeospatialFunctions.R to easily update/replace the new associated test files in the testdata folder as part of routine maintenance if needed (for example, if changes are made to TADA_DataRetrieval)?
> 
> _Great idea, we can change this._
> 
> * I noticed the new functions use the WQP lat/lon columns instead of the TADA versions of those lat/lon columns which are the numeric versions. TADA creates these numeric versions of the lat/lon columns for use in TADA_FlagCoordinates() which looks as the how many numbers are to the right of the decimal and flags lat/lon as imprecise if there are less than 3. That function also flags results outside of the U.S. Let's discuss when to use the original vs TADA lat/lon columns - are both necessary? Keep in mind that the duplicates (originals) may be removed if there is a TADA equivalent and the user wants to reduce number of cols at the end of module 1.
> 
> _Yes, this is something we discussed in the ROSS team, as well! My old justification for using lat/lon (instead of TADA-ified lat/lon) was so that users could run the functions on datasets that weren't created using `autoclean = TRUE`. But, I am inclined to change this now that I see the value of always having TADA.Longitude/TADA.Latitude. For example, I can immediately use those flagging functions you've developed to ensure the geospatial computations are occurring across valid coordinates. (SIDE NOTE: I think this may actually be at least part of the issue that @hillarymarler encountered when running fetchATTAINS across Indiana... there's a wonky observation off the coast of Africa, so the function is trying to pull ATTAINS data across the whole eastern US.)_
> 
> * All columns added typically have the TADA. prefix. TADA For the new ATTAINS columns, the ATTAINS. prefix makes sense. There is one additional column, "geometry" added by these functions. All columns created/referenced in TADA are also all included in the TADA_OrderCols() function in RequiredCols.R. All columns are placed in a specific order and this function is typically run within most TADA functions to keep the order.  Thoughts about changing this to "TADA.Geometry" and placing it near the lat/lon fields in the df column ordering? Is "geometry" better in this case because of how spatial data is referenced in R/sf?
> 
> _Spatial functions automatically store and look for geospatial information in a `geometry` column, so when this gets renamed, it does lead to issues downstream. Though we can rename this column and add code to handle geospatial functions within TADA, it will render the sf object unusable outside of any of the functions we write within this package._
> 
> * Is this message something that we can address or silence? "although coordinates are longitude/latitude, st_intersects assumes that they are planar".
> 
> _I added some messaging suppression as suggested edits!_

Thanks Katie! I created two new issues for the first two so they don't get lost. Let's keep the discussion going there.

For the last one, let's stick with just "geometry" then to avoid those downstream issues. Thanks for the information!

**Pull request merged**
