### PR TITLE
Char ranges eh

### PR DESCRIPTION
**Pull request by ehinman**
Can you take a look and let me know if anything looks wonky? I ran the tests and devtools::check() and everything seems fine, but would like another set of eyes!

### CODE REVIEW

**Comment by katiehealy** [comment]
It looks good to me, but I tried it on a couple example data sets and I'm running into this error with OrderTADACols at the end:
Error in `dplyr::arrange()`:
! Can't transform a data frame with duplicate names.

**Comment by ehinman** [comment]
@katiehealy Thanks for finding this bug! Apparently, it's potentially an issue with the rlang package: https://community.rstudio.com/t/cant-transform-a-data-frame-with-duplicate-names/131688

I switched to a base R command instead, since I worry others might run into the same problem.

**Comment by katiehealy** [comment]
example dataset testing worked! I think you're good to merge :)

**Review by katiehealy — APPROVED** [review]

**Comment by ehinman** [comment]
Thank you!

**Pull request merged**
